In [202]:
import numpy as np

!apt install libgraphviz-dev
!pip install pygraphviz
import networkx as nx

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgail-common libgail18 libgtk2.0-0 libgtk2.0-bin libgtk2.0-common
  libgvc6-plugins-gtk libxdot4
Suggested packages:
  gvfs
The following NEW packages will be installed:
  libgail-common libgail18 libgraphviz-dev libgtk2.0-0 libgtk2.0-bin
  libgtk2.0-common libgvc6-plugins-gtk libxdot4
0 upgraded, 8 newly installed, 0 to remove and 37 not upgraded.
Need to get 2,120 kB of archives.
After this operation, 7,128 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgtk2.0-common all 2.24.32-1ubuntu1 [125 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgtk2.0-0 amd64 2.24.32-1ubuntu1 [1,769 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgail18 amd64 2.24.32-1ubuntu1 [14.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 libgail-common amd64 2.24.32

In [ ]:
class Graph:
'''
    def __init__(self, n_inaccesible, n_accesible, n_supporting):

        self.n_nodes = sum([n_inaccesible, n_accesible, n_supporting]) + 1
        self.adjacency = np.zeros((self.n_nodes, self.n_nodes))

        # fill spammer
        self.adjacency[-n_supporting-1,-n_supporting:] = 1

        # fill accessible to spammer
        self.adjacency[-n_supporting:,-n_supporting-1] = 1

        
        self.adjacency[-n_supporting-1, n_inaccesible:n_inaccesible+n_accesible] = 1

        #
        A = np.random.randint(2, size=(n_accesible+n_supporting,n_inaccesible))

        
        self.adjacency += np.pad(A, pad_width=[(0,self.n_nodes-A.shape[i]) for i in range(2)])
'''

    def __init__(self, G):
        self.G = G
        

        self.transition = self.adjacency.copy()
        for i in range(self.n_nodes):
            n_nodes_in_column = sum(self.transition[:, i])
            if n_nodes_in_column != 0:
                self.transition[:, i] = self.transition[:, i] / n_nodes_in_column

    def get_updated_transition_matrix(self, beta):
        return beta * self.transition + (1-beta) * np.identity(self.n_nodes)

    def get_eigen_vector(self, beta):
        return np.linalg.eig(self.get_updated_transition_matrix(beta))


In [ ]:
graph = Graph(2, 1, 2)
print(graph.adjacency)
print(graph.transition)

[[1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
[[1.  0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.  0. ]
 [0.  0.  1.  0.  1.  1. ]
 [0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0.  0. ]]


In [ ]:
beta = 0.8
values, vectors = graph.get_eigen_vector(beta)

In [ ]:
np.matmul(graph.transition, vectors[:,0])

array([0.        , 0.        , 0.        , 0.81649658, 0.40824829,
       0.40824829])

In [ ]:
values

array([ 1. , -0.6,  0.2,  1. ,  0.2,  0.2])

In [ ]:
i = 3

In [ ]:
np.matmul(graph.get_updated_transition_matrix(beta), vectors[:, i])

array([1., 0., 0., 0., 0., 0.])

In [ ]:
vectors[:, i] * values[i]

array([0.        , 0.        , 0.        , 0.81649658, 0.40824829,
       0.40824829])